import { lazy, type ComponentType, type LazyExoticComponent } from 'react';

export interface DemoMeta {
  name: string;
  title: string;
  description: string;
  requiresWebGPU: boolean;
  color: string; // accent color for gallery card
}

export interface DemoEntry extends DemoMeta {
  component: LazyExoticComponent<ComponentType>;
}

export const demos: DemoEntry[] = [
  {
    name: 'tsl-torus',
    title: 'TSL Torus Knot',
    description: 'Animated torus knot with TSL fresnel glow and color oscillation',
    requiresWebGPU: false,
    color: '#0088ff',
    component: lazy(() => import('../demos/tsl-torus')),
  },
  {
    name: 'particle-field',
    title: 'Particle Field',
    description: '2000 instanced spheres with position-driven color gradients and fresnel glow',
    requiresWebGPU: false,
    color: '#ff44aa',
    component: lazy(() => import('../demos/particle-field')),
  },
  {
    name: 'procedural-terrain',
    title: 'Procedural Terrain',
    description: 'Rolling hills with layered sine-wave displacement and height-based coloring',
    requiresWebGPU: false,
    color: '#1a9926',
    component: lazy(() => import('../demos/procedural-terrain')),
  },
  {
    name: 'crystal-grid',
    title: 'Crystal Grid',
    description: 'Faceted icosahedrons with rainbow wave animation and metallic fresnel rim',
    requiresWebGPU: false,
    color: '#8844ff',
    component: lazy(() => import('../demos/crystal-grid')),
  },
  {
    name: 'aurora-waves',
    title: 'Aurora Waves',
    description: 'Translucent ribbons flowing through green, cyan, purple, and pink',
    requiresWebGPU: false,
    color: '#00ff88',
    component: lazy(() => import('../demos/aurora-waves')),
  },
  {
    name: 'morphing-sphere',
    title: 'Morphing Sphere',
    description: 'Organic alien blob with layered sine-wave vertex displacement',
    requiresWebGPU: false,
    color: '#ff6600',
    component: lazy(() => import('../demos/morphing-sphere')),
  },
  {
    name: 'neon-rings',
    title: 'Neon Rings',
    description: 'Concentric torus rings with pulsing neon emissive glow',
    requiresWebGPU: false,
    color: '#ff00ff',
    component: lazy(() => import('../demos/neon-rings')),
  },
  {
    name: 'ocean-surface',
    title: 'Ocean Surface',
    description: 'Stylized ocean with layered wave displacement and glossy surface',
    requiresWebGPU: false,
    color: '#0066cc',
    component: lazy(() => import('../demos/ocean-surface')),
  },
  {
    name: 'pulse-grid',
    title: 'Pulse Grid',
    description: '400 boxes pulsing in expanding circular ripple waves',
    requiresWebGPU: false,
    color: '#1144aa',
    component: lazy(() => import('../demos/pulse-grid')),
  },
  {
    name: 'spiral-galaxy',
    title: 'Spiral Galaxy',
    description: '3000 instanced stars in three spiral arms with warm-to-cool gradient',
    requiresWebGPU: false,
    color: '#ffcc44',
    component: lazy(() => import('../demos/spiral-galaxy')),
  },
  {
    name: 'flame-orb',
    title: 'Flame Orb',
    description: 'Sphere with aggressive fire-like flickering and warm emission',
    requiresWebGPU: false,
    color: '#ff3300',
    component: lazy(() => import('../demos/flame-orb')),
  },
  {
    name: 'dna-helix',
    title: 'DNA Helix',
    description: 'Double helix of instanced spheres with blue-red gradient and connecting rungs',
    requiresWebGPU: false,
    color: '#4488ff',
    component: lazy(() => import('../demos/dna-helix')),
  },
  {
    name: 'wireframe-landscape',
    title: 'Wireframe Landscape',
    description: 'Retro Tron-style scrolling wireframe terrain with neon glow',
    requiresWebGPU: false,
    color: '#00ffff',
    component: lazy(() => import('../demos/wireframe-landscape')),
  },
  {
    name: 'plasma-globe',
    title: 'Plasma Globe',
    description: 'Electric purple-blue sphere with swirling plasma discharge patterns',
    requiresWebGPU: false,
    color: '#6600ff',
    component: lazy(() => import('../demos/plasma-globe')),
  },
  {
    name: 'ribbon-dance',
    title: 'Ribbon Dance',
    description: 'Colorful ribbons twisting and spiraling through space',
    requiresWebGPU: false,
    color: '#ff2244',
    component: lazy(() => import('../demos/ribbon-dance')),
  },
  {
    name: 'noise-dissolve',
    title: 'Noise Dissolve',
    description: 'Dodecahedron dissolving and reforming with hash noise, burning edges, and fresnel rim',
    requiresWebGPU: false,
    color: '#ee8833',
    component: lazy(() => import('../demos/noise-dissolve')),
  },
  {
    name: 'screen-hologram',
    title: 'Screen Hologram',
    description: 'Holographic projection with screen-space scanlines, glitch bands, and fresnel rim glow',
    requiresWebGPU: false,
    color: '#22ddcc',
    component: lazy(() => import('../demos/screen-hologram')),
  },
  {
    name: 'uv-kaleidoscope',
    title: 'UV Kaleidoscope',
    description: 'Procedural mandala with polar UV folding, spherize warping, and animated concentric patterns',
    requiresWebGPU: false,
    color: '#dd2288',
    component: lazy(() => import('../demos/uv-kaleidoscope')),
  },
  {
    name: 'bloom-orbs',
    title: 'Bloom Orbs',
    description: 'Floating orbs with TSL-driven glow halos, fresnel rims, additive blending, and pulsing emissive bloom',
    requiresWebGPU: false,
    color: '#ccff00',
    component: lazy(() => import('../demos/bloom-orbs')),
  },
  {
    name: 'sprite-sparks',
    title: 'Sprite Sparks',
    description: 'Billboard point-sprite particle fountain with TSL-driven size, color gradients, and pulsing opacity',
    requiresWebGPU: false,
    color: '#ff8844',
    component: lazy(() => import('../demos/sprite-sparks')),
  },
  {
    name: 'volumetric-cloud',
    title: 'Volumetric Cloud',
    description: 'Layered shell volumetric nebula with TSL Fn() noise-driven density, animated swirling, and warm-to-cool emissive glow',
    requiresWebGPU: false,
    color: '#aa44cc',
    component: lazy(() => import('../demos/volumetric-cloud')),
  },
  {
    name: 'multi-material',
    title: 'Multi-Material',
    description: 'Cube assembled from 6 planes, each with a unique TSL material: fire, ice, electric, gold, nature, and plasma',
    requiresWebGPU: false,
    color: '#33cc99',
    component: lazy(() => import('../demos/multi-material')),
  },
  {
    name: 'compute-particles',
    title: 'Compute Particles',
    description: '20,000 GPU-driven particles with compute shader physics, gravity, respawn, and velocity-based color',
    requiresWebGPU: true,
    color: '#ff5577',
    component: lazy(() => import('../demos/compute-particles')),
  },
  {
    name: 'resolution-warp',
    title: 'Resolution Warp',
    description: 'CRT pixelation sphere using TSL screenSize for pixel-scale grids, phosphor sub-pixels, scanlines, and moiré patterns',
    requiresWebGPU: false,
    color: '#44bbdd',
    component: lazy(() => import('../demos/resolution-warp')),
  },
  {
    name: 'skeletal-wave',
    title: 'Skeletal Wave',
    description: 'Programmatic skinned mesh tentacles with CPU-driven bone animation and TSL height-based color gradients',
    requiresWebGPU: false,
    color: '#bb44ff',
    component: lazy(() => import('../demos/skeletal-wave')),
  },
  {
    name: 'galaxy-collision',
    title: 'Galaxy Collision',
    description: 'Two spiral galaxies collide with GPU compute gravity driving 10000+ stars',
    requiresWebGPU: true,
    color: '#2244aa',
    component: lazy(() => import('../demos/galaxy-collision')),
  },
  {
    name: 'fractal-zoom',
    title: 'Fractal Zoom',
    description: 'Mandelbrot set with infinite zoom, smooth coloring, and cycling vivid gradients rendered in TSL',
    requiresWebGPU: false,
    color: '#ff6622',
    component: lazy(() => import('../demos/fractal-zoom')),
  },
  {
    name: 'fluid-sim',
    title: 'Fluid Simulation',
    description: '256x256 GPU compute fluid with semi-Lagrangian advection, vorticity confinement, and multi-color dye injection',
    requiresWebGPU: true,
    color: '#11ccaa',
    component: lazy(() => import('../demos/fluid-sim')),
  },
  {
    name: 'procedural-planet',
    title: 'Procedural Planet',
    description: 'Rotating planet with hash-noise biome coloring, transparent cloud layer, atmospheric fresnel glow, and instanced starfield',
    requiresWebGPU: false,
    color: '#2288aa',
    component: lazy(() => import('../demos/procedural-planet')),
  },
  {
    name: 'waveform-viz',
    title: 'Waveform Visualizer',
    description: 'Concentric rings of instanced spheres deform to simulated audio frequencies with intensity-driven color shifts',
    requiresWebGPU: false,
    color: '#0055ee',
    component: lazy(() => import('../demos/waveform-viz')),
  },
  {
    name: 'cyber-city',
    title: 'Cyber City',
    description: 'Procedural cyberpunk skyline with 350 instanced neon buildings, reflective ground plane, and atmospheric fog',
    requiresWebGPU: false,
    color: '#ff1177',
    component: lazy(() => import('../demos/cyber-city')),
  },
  {
    name: 'deep-sea',
    title: 'Deep Sea',
    description: 'Bioluminescent jellyfish with chain tentacles, luminous plankton, volumetric light shafts, and depth fog',
    requiresWebGPU: false,
    color: '#00aacc',
    component: lazy(() => import('../demos/deep-sea')),
  },
  {
    name: 'particle-morph',
    title: 'Particle Morph',
    description: '5000 particles morphing between sphere, cube, torus, and icosahedron with spring physics',
    requiresWebGPU: false,
    color: '#00ddaa',
    component: lazy(() => import('../demos/particle-morph')),
  },
  {
    name: 'black-hole',
    title: 'Black Hole',
    description: 'Event horizon with gravitational lensing, swirling accretion disk, photon ring, and warped starfield',
    requiresWebGPU: false,
    color: '#221133',
    component: lazy(() => import('../demos/black-hole')),
  },
  {
    name: 'neural-net',
    title: 'Neural Network',
    description: '5-layer neural network with 48 nodes, 420 glowing edges, and traveling data pulses',
    requiresWebGPU: false,
    color: '#44ccbb',
    component: lazy(() => import('../demos/neural-net')),
  },
  {
    name: 'test-scene',
    title: 'Test Scene (Pipeline)',
    description: 'Integration test: terrain, rocks, and CSG archway rendered from scene YAML',
    requiresWebGPU: false,
    color: '#66aa44',
    component: lazy(() => import('../demos/test-scene')),
  },
  {
    name: 'junkyard',
    title: 'Abandoned Junkyard',
    description: 'Post-apocalyptic junkyard with rusted vehicles, debris piles, CSG barriers, and scattered rocks',
    requiresWebGPU: false,
    color: '#8B6914',
    component: lazy(() => import('../demos/junkyard')),
  },
  {
    name: 'alien-garden',
    title: 'Alien Garden',
    description: 'Bioluminescent alien garden with glowing mushrooms, exotic vegetation, and SDF organic shapes',
    requiresWebGPU: false,
    color: '#6622cc',
    component: lazy(() => import('../demos/alien-garden')),
  },
  {
    name: 'medieval-forge',
    title: 'Medieval Forge',
    description: 'Blacksmith workshop with forge fire, weapon rack, anvil workbench, and scattered debris',
    requiresWebGPU: false,
    color: '#cc6622',
    component: lazy(() => import('../demos/medieval-forge')),
  },
  {
    name: 'underwater-ruins',
    title: 'Underwater Ruins',
    description: 'Submerged ancient temple with broken columns, coral growths, kelp, and bioluminescent lighting',
    requiresWebGPU: false,
    color: '#1177aa',
    component: lazy(() => import('../demos/underwater-ruins')),
  },
  {
    name: 'cyberpunk-street',
    title: 'Cyberpunk Street',
    description: 'Neon-lit urban night scene with tower buildings, parked vehicles, vendor stall, and dense purple fog',
    requiresWebGPU: false,
    color: '#ee11aa',
    component: lazy(() => import('../demos/cyberpunk-street')),
  },
  {
    name: 'desert-outpost',
    title: 'Desert Outpost',
    description: 'Remote desert camp with outpost building, rock formations, old truck, and supply crates',
    requiresWebGPU: false,
    color: '#cc8833',
    component: lazy(() => import('../demos/desert-outpost')),
  },
  {
    name: 'robot-factory',
    title: 'Robot Factory',
    description: 'Automated manufacturing floor with robot workers, workbenches, pipes, and industrial lighting',
    requiresWebGPU: false,
    color: '#4488cc',
    component: lazy(() => import('../demos/robot-factory')),
  },
  {
    name: 'crystal-cavern',
    title: 'Crystal Cavern',
    description: 'Underground cave with glowing crystal clusters, hash-noise cave walls, fresnel refraction, bloom halos, and colored point lights',
    requiresWebGPU: false,
    color: '#9944cc',
    component: lazy(() => import('../demos/crystal-cavern')),
  },
  {
    name: 'time-vortex',
    title: 'Time Vortex',
    description: 'Spiraling temporal distortion with SDF vortex funnel, compute-driven particles, clock elements, gravitational UV warping, and bloom halos',
    requiresWebGPU: true,
    color: '#ddaa33',
    component: lazy(() => import('../demos/time-vortex')),
  },
  {
    name: 'enchanted-forest',
    title: 'Enchanted Forest',
    description: 'Magical woodland with giant glowing mushrooms, dense trees, mossy boulders, and ancient stone arch',
    requiresWebGPU: false,
    color: '#22bb44',
    component: lazy(() => import('../demos/enchanted-forest')),
  },
  {
    name: 'space-station',
    title: 'Space Station',
    description: 'Sci-fi corridor with holographic displays, alien specimen, pipe conduits, and cool fluorescent lighting',
    requiresWebGPU: false,
    color: '#3366dd',
    component: lazy(() => import('../demos/space-station')),
  },
  {
    name: 'gladiator-arena',
    title: 'Gladiator Arena',
    description: 'Roman colosseum floor with arena walls, two gladiators with weapons, rubble, and harsh midday sun',
    requiresWebGPU: false,
    color: '#bb8844',
    component: lazy(() => import('../demos/gladiator-arena')),
  },
  {
    name: 'cosmic-jellyfish',
    title: 'Cosmic Jellyfish',
    description: 'Bioluminescent space jellyfish with bone-animated tentacles, volumetric dome, bloom halos, and compute-driven particle trails',
    requiresWebGPU: true,
    color: '#00eebb',
    component: lazy(() => import('../demos/cosmic-jellyfish')),
  },
  {
    name: 'digital-storm',
    title: 'Digital Storm',
    description: 'Full-viewport storm with compute wind-driven rain, fractal lightning branches, SDF cloud layer, and ambient flash bloom',
    requiresWebGPU: true,
    color: '#5533bb',
    component: lazy(() => import('../demos/digital-storm')),
  },
  {
    name: 'lava-planet',
    title: 'Lava Planet',
    description: 'Molten planet with hash noise lava cracks, atmospheric halo shells, and 250 orbiting debris rocks',
    requiresWebGPU: false,
    color: '#ff3300',
    component: lazy(() => import('../demos/lava-planet')),
  },
  {
    name: 'cyber-tunnel',
    title: 'Cyber Tunnel',
    description: 'Infinite SDF hexagonal tunnel fly-through with neon rings, speed lines, and color cycling',
    requiresWebGPU: false,
    color: '#ff22cc',
    component: lazy(() => import('../demos/cyber-tunnel')),
  },
  {
    name: 'aurora-cascade',
    title: 'Aurora Cascade',
    description: '1200 compute-driven aurora strips with 5-stop color gradient, ground reflections, and bloom sky glow',
    requiresWebGPU: true,
    color: '#00ff66',
    component: lazy(() => import('../demos/aurora-cascade')),
  },
  {
    name: 'particle-galaxy-portrait',
    title: 'Particle Galaxy Portrait',
    description: '10000 compute particles forming a skull shape with proximity-based coloring and orbital shimmer',
    requiresWebGPU: true,
    color: '#3355ff',
    component: lazy(() => import('../demos/particle-galaxy-portrait')),
  },
  {
    name: 'quantum-field',
    title: 'Quantum Field',
    description: '8000 compute particles with Brownian motion and periodic wave function collapse flash',
    requiresWebGPU: true,
    color: '#4477ff',
    component: lazy(() => import('../demos/quantum-field')),
  },
  {
    name: 'phoenix-rising',
    title: 'Phoenix Rising',
    description: 'Flaming bird with bone-animated wings, dissolve fire effect, 1500 trailing particles, and falling ash',
    requiresWebGPU: false,
    color: '#ff4400',
    component: lazy(() => import('../demos/phoenix-rising')),
  },
  {
    name: 'reaction-diffusion',
    title: 'Reaction Diffusion',
    description: 'Gray-Scott reaction-diffusion model producing organic Turing patterns on a 256x256 GPU compute grid',
    requiresWebGPU: true,
    color: '#22bbaa',
    component: lazy(() => import('../demos/reaction-diffusion')),
  },
  {
    name: 'boids-murmuration',
    title: 'Boids Murmuration',
    description: '10,000 bird-like particles flocking via GPU compute with separation, alignment, and cohesion rules',
    requiresWebGPU: true,
    color: '#6644ff',
    component: lazy(() => import('../demos/boids-murmuration')),
  },
  {
    name: 'interference-waves',
    title: 'Interference Waves',
    description: 'Multiple wave sources creating constructive/destructive interference patterns with rainbow color mapping',
    requiresWebGPU: false,
    color: '#00ddff',
    component: lazy(() => import('../demos/interference-waves')),
  },
  {
    name: 'cellular-life',
    title: 'Cellular Life',
    description: '256x256 Game of Life cellular automaton with GPU compute double-buffered grid and age-based coloring',
    requiresWebGPU: true,
    color: '#44ff22',
    component: lazy(() => import('../demos/cellular-life')),
  },
  {
    name: 'pendulum-wave',
    title: 'Pendulum Wave',
    description: '20 pendulums with slightly different periods creating mesmerizing wave patterns as they drift in and out of phase',
    requiresWebGPU: false,
    color: '#ff8800',
    component: lazy(() => import('../demos/pendulum-wave')),
  },
  {
    name: 'terrain-erosion',
    title: 'Terrain Erosion',
    description: '128x128 GPU compute hydraulic erosion with rain, water flow, sediment transport, and height-based terrain coloring',
    requiresWebGPU: true,
    color: '#886633',
    component: lazy(() => import('../demos/terrain-erosion')),
  },
  {
    name: 'gravitational-orbits',
    title: 'Gravitational Orbits',
    description: '5000 particles orbiting 4 moving attractors with GPU compute gravitational forces and speed-based color',
    requiresWebGPU: true,
    color: '#ffaa22',
    component: lazy(() => import('../demos/gravitational-orbits')),
  },
  {
    name: 'voronoi-shatter',
    title: 'Voronoi Shatter',
    description: 'Animated Voronoi cell pattern on a sphere with neon crack lines, per-cell coloring, and pulsing emissive edges',
    requiresWebGPU: false,
    color: '#ff3366',
    component: lazy(() => import('../demos/voronoi-shatter')),
  },
  {
    name: 'smoke-tendrils',
    title: 'Smoke Tendrils',
    description: '6000 wispy smoke particles rising and curling with GPU compute curl-noise turbulence',
    requiresWebGPU: true,
    color: '#aaaaaa',
    component: lazy(() => import('../demos/smoke-tendrils')),
  },
  {
    name: 'sdf-morphscape',
    title: 'SDF Morphscape',
    description: 'Raymarched SDF landscape of morphing geometric primitives blending with smooth unions',
    requiresWebGPU: false,
    color: '#9944cc',
    component: lazy(() => import('../demos/sdf-morphscape')),
  },
  {
    name: 'forge-lifecycle',
    title: 'Forge Lifecycle',
    description: 'Interactive 3D visualization of the Forge developer workflow with clickable phases, orbiting skills, and particle flow connections',
    requiresWebGPU: false,
    color: '#22cc88',
    component: lazy(() => import('../demos/forge-lifecycle')),
  },
  {
    name: 'decision-forest',
    title: 'Decision Forest',
    description: 'Forge drive decision tree as a 3D branching structure with click-to-highlight paths and flowing edge particles',
    requiresWebGPU: false,
    color: '#ffaa22',
    component: lazy(() => import('../demos/decision-forest')),
  },
  {
    name: 'dependency-graph-3d',
    title: 'Dependency Graph 3D',
    description: 'Force-directed 3D graph of package dependencies with click-to-select nodes, edge highlighting, and smooth camera transitions',
    requiresWebGPU: false,
    color: '#61dafb',
    component: lazy(() => import('../demos/dependency-graph-3d')),
  },
  {
    name: 'code-constellation',
    title: 'Code Constellation',
    description: 'Codebase files as a star constellation with directory clusters, import connections, type-based coloring, and zoom-to-cluster interactivity',
    requiresWebGPU: false,
    color: '#3178c6',
    component: lazy(() => import('../demos/code-constellation')),
  },
  {
    name: 'neural-pipeline-flow',
    title: 'Neural Pipeline Flow',
    description: 'Interactive AI inference pipeline with transformer stages, flowing data particles, and click-to-zoom detail views',
    requiresWebGPU: false,
    color: '#44aaff',
    component: lazy(() => import('../demos/neural-pipeline-flow')),
  },
  {
    name: 'data-flow-pipes',
    title: 'Data Flow Pipes',
    description: 'Data transformation pipeline with filtering, merging, splitting, and 300 particles flowing through a 3D pipe network',
    requiresWebGPU: false,
    color: '#cc44ff',
    component: lazy(() => import('../demos/data-flow-pipes')),
  },
  {
    name: 'state-machine-3d',
    title: 'State Machine 3D',
    description: 'Interactive state machine diagram showing a Forge project lifecycle with clickable transitions and animated particles',
    requiresWebGPU: false,
    color: '#ffaa22',
    component: lazy(() => import('../demos/state-machine-3d')),
  },
  {
    name: 'architecture-blueprint',
    title: 'Architecture Blueprint',
    description: 'System architecture diagram with 3D floating service platforms, animated data flow particles, and interactive zoom',
    requiresWebGPU: false,
    color: '#4488ff',
    component: lazy(() => import('../demos/architecture-blueprint')),
  },
  {
    name: 'timeline-helix',
    title: 'Timeline Helix',
    description: 'Project timeline rendered as a DNA-like double helix with clickable event spheres, traveling particles, and type-colored rungs',
    requiresWebGPU: false,
    color: '#ff4488',
    component: lazy(() => import('../demos/timeline-helix')),
  },
  {
    name: 'metric-terrain',
    title: 'Metric Terrain',
    description: 'Data metrics visualized as 3D terrain with height-mapped values, sweeping time cursor, and interactive peak markers',
    requiresWebGPU: false,
    color: '#ffaa22',
    component: lazy(() => import('../demos/metric-terrain')),
  },
  {
    name: 'beat-pulse-grid',
    title: 'Beat Pulse Grid',
    description: '400 pillars pulsing to simulated beat frequencies with bass-reactive height and color gradient',
    requiresWebGPU: false,
    color: '#ff2266',
    component: lazy(() => import('../demos/beat-pulse-grid')),
  },
  {
    name: 'frequency-mountains',
    title: 'Frequency Mountains',
    description: '3D terrain with vertex displacement driven by simulated 64-band frequency spectrum',
    requiresWebGPU: false,
    color: '#4400ff',
    component: lazy(() => import('../demos/frequency-mountains')),
  },
  {
    name: 'waveform-tunnel',
    title: 'Waveform Tunnel',
    description: 'Fly-through tunnel with walls deforming to scrolling waveform sine patterns',
    requiresWebGPU: false,
    color: '#00ffaa',
    component: lazy(() => import('../demos/waveform-tunnel')),
  },
  {
    name: 'synth-aurora',
    title: 'Synth Aurora',
    description: 'Aurora ribbon curtains with color and sway driven by simulated synthesizer tones',
    requiresWebGPU: false,
    color: '#8800ff',
    component: lazy(() => import('../demos/synth-aurora')),
  },
  {
    name: 'drum-machine-cubes',
    title: 'Drum Machine Cubes',
    description: '4x4 instrument grid with cubes triggering scale and emissive pulses on rhythmic beat patterns',
    requiresWebGPU: false,
    color: '#ff8800',
    component: lazy(() => import('../demos/drum-machine-cubes')),
  },
  {
    name: 'bass-nebula',
    title: 'Bass Nebula',
    description: 'Volumetric shell cloud pulsing radius and opacity to simulated bass frequency',
    requiresWebGPU: false,
    color: '#2200aa',
    component: lazy(() => import('../demos/bass-nebula')),
  },
  {
    name: 'vinyl-grooves',
    title: 'Vinyl Grooves',
    description: 'Spinning vinyl record with concentric groove displacement and tonearm animation',
    requiresWebGPU: false,
    color: '#cc8800',
    component: lazy(() => import('../demos/vinyl-grooves')),
  },
  {
    name: 'equalizer-city',
    title: 'Equalizer City',
    description: 'Cityscape of 200 instanced buildings with heights animated by simulated frequency band data',
    requiresWebGPU: false,
    color: '#ff0066',
    component: lazy(() => import('../demos/equalizer-city')),
  },
  {
    name: 'piano-waterfall',
    title: 'Piano Waterfall',
    description: '88-key MIDI waterfall with cascading note blocks and velocity-based glow',
    requiresWebGPU: false,
    color: '#0088ff',
    component: lazy(() => import('../demos/piano-waterfall')),
  },
  {
    name: 'sonic-bloom',
    title: 'Sonic Bloom',
    description: 'Procedural flowers that bloom and pulse in response to simulated harmonic overtone series',
    requiresWebGPU: false,
    color: '#ff44ff',
    component: lazy(() => import('../demos/sonic-bloom')),
  },
  {
    name: 'cloth-wind',
    title: 'Cloth in Wind',
    description: 'GPU compute cloth simulation with 64x64 particle grid, spring constraints, wind forces, and pinned top edge',
    requiresWebGPU: true,
    color: '#44aaff',
    component: lazy(() => import('../demos/cloth-wind')),
  },
  {
    name: 'soft-body-bounce',
    title: 'Soft Body Bounce',
    description: 'Deformable pressure-based soft body sphere bouncing off a floor with stress-based coloring',
    requiresWebGPU: true,
    color: '#ff6644',
    component: lazy(() => import('../demos/soft-body-bounce')),
  },
  {
    name: 'rope-bridge',
    title: 'Rope Bridge',
    description: 'Verlet integration rope bridge with gravity, wind sway, fixed endpoints, and plank segments',
    requiresWebGPU: false,
    color: '#88cc22',
    component: lazy(() => import('../demos/rope-bridge')),
  },
  {
    name: 'fluid-pressure',
    title: 'Fluid Pressure',
    description: 'SPH-inspired fluid particles with pressure forces, viscosity, and container boundaries',
    requiresWebGPU: true,
    color: '#2288ff',
    component: lazy(() => import('../demos/fluid-pressure')),
  },
  {
    name: 'ragdoll-fall',
    title: 'Ragdoll Fall',
    description: 'Articulated stick figure with joint constraints tumbling through horizontal bar obstacles',
    requiresWebGPU: false,
    color: '#ff4488',
    component: lazy(() => import('../demos/ragdoll-fall')),
  },
  {
    name: 'spring-mesh',
    title: 'Spring Mesh',
    description: 'Spring-connected grid that ripples and deforms from periodic impact points with height-based coloring',
    requiresWebGPU: true,
    color: '#44ffaa',
    component: lazy(() => import('../demos/spring-mesh')),
  },
  {
    name: 'magnetic-fields',
    title: 'Magnetic Fields',
    description: '3000 particles tracing magnetic field lines between dipole pairs with field-strength coloring',
    requiresWebGPU: true,
    color: '#8844ff',
    component: lazy(() => import('../demos/magnetic-fields')),
  },
  {
    name: 'collision-cascade',
    title: 'Collision Cascade',
    description: 'Chain reaction of 200 rigid spheres with elastic collision response and kinetic energy coloring',
    requiresWebGPU: true,
    color: '#ffaa00',
    component: lazy(() => import('../demos/collision-cascade')),
  },
  {
    name: 'elastic-waves',
    title: 'Elastic Waves',
    description: '2D wave equation on 128x128 grid with compute-driven propagation and periodic point-source disturbances',
    requiresWebGPU: true,
    color: '#00aaff',
    component: lazy(() => import('../demos/elastic-waves')),
  },
  {
    name: 'pendulum-chaos',
    title: 'Pendulum Chaos',
    description: 'Triple pendulum with chaotic diverging trajectories, RK4 integration, and trail rendering',
    requiresWebGPU: false,
    color: '#ff2244',
    component: lazy(() => import('../demos/pendulum-chaos')),
  },
  {
    name: 'infinite-terrain',
    title: 'Infinite Terrain',
    description: 'Endless scrolling terrain with multi-octave noise displacement, 4 biomes, and LOD detail rings',
    requiresWebGPU: false,
    color: '#44aa22',
    component: lazy(() => import('../demos/infinite-terrain')),
  },
  {
    name: 'city-generator',
    title: 'City Generator',
    description: 'Procedural city blocks with roads, varied building heights, neon window lights, and traffic signals',
    requiresWebGPU: false,
    color: '#ff6600',
    component: lazy(() => import('../demos/city-generator')),
  },
  {
    name: 'cave-system',
    title: 'Cave System',
    description: 'Underground cave with noise-carved walls, stalactites, bioluminescent pools, and crystal clusters',
    requiresWebGPU: false,
    color: '#664422',
    component: lazy(() => import('../demos/cave-system')),
  },
  {
    name: 'floating-islands',
    title: 'Floating Islands',
    description: 'Sky islands with waterfalls, vegetation tufts, cloud wisps, and atmospheric depth',
    requiresWebGPU: false,
    color: '#44ccff',
    component: lazy(() => import('../demos/floating-islands')),
  },
  {
    name: 'ocean-world',
    title: 'Ocean World',
    description: 'Vast animated ocean with multi-layer wave displacement, foam lines, and underwater caustic patterns',
    requiresWebGPU: false,
    color: '#0066aa',
    component: lazy(() => import('../demos/ocean-world')),
  },
  {
    name: 'desert-dunes',
    title: 'Desert Dunes',
    description: 'Wind-sculpted sand dune field with ripple displacement, heat haze, and drifting sand particles',
    requiresWebGPU: false,
    color: '#cc9944',
    component: lazy(() => import('../demos/desert-dunes')),
  },
  {
    name: 'ice-fortress',
    title: 'Ice Fortress',
    description: 'Crystalline ice structures with fresnel refraction glow, sub-surface lighting, and frost particles',
    requiresWebGPU: false,
    color: '#88ddff',
    component: lazy(() => import('../demos/ice-fortress')),
  },
  {
    name: 'mushroom-forest',
    title: 'Mushroom Forest',
    description: 'Giant bioluminescent mushrooms with pulsing caps, spore particles, and ground fog',
    requiresWebGPU: false,
    color: '#22cc88',
    component: lazy(() => import('../demos/mushroom-forest')),
  },
  {
    name: 'volcanic-rift',
    title: 'Volcanic Rift',
    description: 'Lava river through cracked terrain with smoke particles, ember sparks, and heat distortion',
    requiresWebGPU: false,
    color: '#ff3300',
    component: lazy(() => import('../demos/volcanic-rift')),
  },
  {
    name: 'alien-megastructure',
    title: 'Alien Megastructure',
    description: 'Non-euclidean architecture with nested rotating frames, energy conduits, and portal distortion',
    requiresWebGPU: false,
    color: '#aa22ff',
    component: lazy(() => import('../demos/alien-megastructure')),
  },
  {
    name: 'crt-monitor',
    title: 'CRT Monitor',
    description: 'Full CRT simulation with scanlines, phosphor glow, barrel distortion, vignette, and color bleed',
    requiresWebGPU: false,
    color: '#33ff33',
    component: lazy(() => import('../demos/crt-monitor')),
  },
  {
    name: 'vhs-glitch',
    title: 'VHS Glitch',
    description: 'VHS tape degradation with tracking errors, chromatic aberration, noise bands, and color shift',
    requiresWebGPU: false,
    color: '#ff3333',
    component: lazy(() => import('../demos/vhs-glitch')),
  },
  {
    name: 'synthwave-grid',
    title: 'Synthwave Grid',
    description: '80s retrowave infinite perspective grid with neon sun, mountain silhouette, and chrome aesthetic',
    requiresWebGPU: false,
    color: '#ff00ff',
    component: lazy(() => import('../demos/synthwave-grid')),
  },
  {
    name: 'pixel-dissolve',
    title: 'Pixel Dissolve',
    description: '3D scene progressively pixelating with color quantization and ordered dithering at the transition edge',
    requiresWebGPU: false,
    color: '#00ff88',
    component: lazy(() => import('../demos/pixel-dissolve')),
  },
  {
    name: 'demoscene-plasma',
    title: 'Demoscene Plasma',
    description: 'Classic demo plasma effect with layered sine wave interference and 8-stop cycling color palette',
    requiresWebGPU: false,
    color: '#ff8800',
    component: lazy(() => import('../demos/demoscene-plasma')),
  },
  {
    name: 'ascii-render',
    title: 'ASCII Render',
    description: '3D scene rendered as ASCII characters via luminance-to-glyph mapping with terminal aesthetic',
    requiresWebGPU: false,
    color: '#00ff00',
    component: lazy(() => import('../demos/ascii-render')),
  },
  {
    name: 'neon-noir',
    title: 'Neon Noir',
    description: 'Rain-soaked neon street with wet reflections, volumetric light cones, and film noir palette',
    requiresWebGPU: false,
    color: '#ff0044',
    component: lazy(() => import('../demos/neon-noir')),
  },
  {
    name: 'gameboy-shader',
    title: 'Gameboy Shader',
    description: 'DMG-style 4-color rendering with ordered dithering, LCD pixel grid, and screen border frame',
    requiresWebGPU: false,
    color: '#88bb22',
    component: lazy(() => import('../demos/gameboy-shader')),
  },
  {
    name: 'vector-arcade',
    title: 'Vector Arcade',
    description: 'Wireframe vector graphics with phosphor glow trails in Asteroids/Tempest aesthetic',
    requiresWebGPU: false,
    color: '#00ffff',
    component: lazy(() => import('../demos/vector-arcade')),
  },
  {
    name: 'glitch-portrait',
    title: 'Glitch Portrait',
    description: 'Abstract face mesh with block displacement, RGB split, scan distortion, and periodic glitch bursts',
    requiresWebGPU: false,
    color: '#ff22aa',
    component: lazy(() => import('../demos/glitch-portrait')),
  },
  {
    name: 'tree-growth',
    title: 'Tree Growth',
    description: 'L-system tree growing in real time with branching cylinders, leaf particles, and wind sway',
    requiresWebGPU: false,
    color: '#228822',
    component: lazy(() => import('../demos/tree-growth')),
  },
  {
    name: 'coral-reef',
    title: 'Coral Reef',
    description: 'Branching coral structures with swaying anemones, swimming fish, and caustic floor lighting',
    requiresWebGPU: false,
    color: '#ff8844',
    component: lazy(() => import('../demos/coral-reef')),
  },
  {
    name: 'weather-system',
    title: 'Weather System',
    description: 'Cycling weather states with volumetric clouds, compute-driven rain, lightning, and dynamic lighting',
    requiresWebGPU: true,
    color: '#4488cc',
    component: lazy(() => import('../demos/weather-system')),
  },
  {
    name: 'crystal-formation',
    title: 'Crystal Formation',
    description: 'Crystals growing from seed points with animated extension, branching, and refraction glow',
    requiresWebGPU: false,
    color: '#aa44ff',
    component: lazy(() => import('../demos/crystal-formation')),
  },
  {
    name: 'mycelium-network',
    title: 'Mycelium Network',
    description: 'Underground fungal network spreading tendrils with nutrient pulse particles and bioluminescent fruiting bodies',
    requiresWebGPU: false,
    color: '#ccaa22',
    component: lazy(() => import('../demos/mycelium-network')),
  },
  {
    name: 'butterfly-swarm',
    title: 'Butterfly Swarm',
    description: 'Morpho butterflies with iridescent fresnel wings, flocking behavior, and garden backdrop',
    requiresWebGPU: false,
    color: '#2288ff',
    component: lazy(() => import('../demos/butterfly-swarm')),
  },
  {
    name: 'flower-bloom',
    title: 'Flower Bloom',
    description: 'Time-lapse flower opening with petal unfurling animation, stem growth, and floating pollen',
    requiresWebGPU: false,
    color: '#ff66aa',
    component: lazy(() => import('../demos/flower-bloom')),
  },
  {
    name: 'erosion-canyon',
    title: 'Erosion Canyon',
    description: 'Hydraulic erosion carving a canyon with layered rock strata, river flow, and rim vegetation',
    requiresWebGPU: true,
    color: '#aa6633',
    component: lazy(() => import('../demos/erosion-canyon')),
  },
  {
    name: 'frost-patterns',
    title: 'Frost Patterns',
    description: 'DLA ice crystal formation on glass with branching structures and warm background glow',
    requiresWebGPU: true,
    color: '#88ccff',
    component: lazy(() => import('../demos/frost-patterns')),
  },
  {
    name: 'kelp-forest',
    title: 'Kelp Forest',
    description: 'Underwater kelp strands swaying in current with light shafts, fish, and rising bubbles',
    requiresWebGPU: false,
    color: '#22aa44',
    component: lazy(() => import('../demos/kelp-forest')),
  },
];

export function getDemoByName(name: string): DemoEntry | undefined {
  return demos.find((d) => d.name === name);
}

export function getAdjacentDemos(name: string): { prev: DemoEntry | null; next: DemoEntry | null } {
  const idx = demos.findIndex((d) => d.name === name);
  if (idx === -1) return { prev: null, next: null };
  return {
    prev: idx > 0 ? demos[idx - 1] : demos[demos.length - 1],
    next: idx < demos.length - 1 ? demos[idx + 1] : demos[0],
  };
}
